#eureka:
#    client:
#        serviceUrl:
#            defaultZone:  ${EUREKA_URI:http://10.10.10.175:8761/eureka}
#    instance:
#        lease-renewal-interval-in-seconds: 30
#        preferIpAddress: true
logging:
    level:
      web: info
    file:
        name: logs/sap.log
        path: logs
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36}:%L - %msg%n'
        file: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36}:%L - %msg%n'
server:
    error:
        whitelabel:
            enabled: false
    port: 8080
spring:
    application:
        name: sap
    devtools:
     add-properties : false  
    datasource:
        driver-class-name: com.edb.Driver
        jdbc-url: ${JDBC_URL:jdbc:edb://10.10.10.94:5444/bpcl}
        maximum-pool-size: ${POLL_SIZE:1}
        password: ${DB_PWD:enterprisedb123}
        testWhileIdle: true
        username: ${DB_USER:enterprisedb}
        validationQuery: SELECT 1

    jpa:
        properties:
            hibernate:
                format_sql: false
                #globally_quoted_identifiers: true
                show_sql: false
                use_sql_comments: false
    codec: 
      max-in-memory-size: 10MB